In [ ]:
import numpy as np
import sys

def display_npz(file_path):
    try:
        with np.load(file_path,allow_pickle=True) as data:
            print(f"文件 '{file_path}' 包含以下数组：")
            for key in data.files:
                array = data[key]
                print("\n" + "=" * 50)
                print(f"数组名称: {key}")
                print(f"形状: {array.shape}")
                print(f"数据类型: {array.dtype}")
                print("\n数据示例:")
                print(array)
    except FileNotFoundError:
        print(f"错误：文件 '{file_path}' 不存在。")
    except Exception as e:
        print(f"读取文件时发生错误：{e}")

if __name__ == "__main__":
    display_npz("NAB-known-anomaly/machine_temp.npz")

文件 'NAB-known-anomaly/machine_temp.npz' 包含以下数组：

数组名称: t
形状: (22695,)
数据类型: int64

数据示例:
[    1     2     3 ... 22693 22694 22695]

数组名称: t_unit
形状: ()
数据类型: <U5

数据示例:
5 min

数组名称: readings
形状: (22695,)
数据类型: float64

数据示例:
[73.96732207 74.935882   76.12416182 ... 97.13546835 98.05685212
 96.90386085]

数组名称: idx_anomaly
形状: (4,)
数据类型: int64

数据示例:
[ 2410  3987 16341 19516]

数组名称: idx_split
形状: (2,)
数据类型: int64

数据示例:
[ 5000 15500]

数组名称: training
形状: (10500,)
数据类型: float64

数据示例:
[ 0.92998037  1.00407031  1.02560371 ... -1.21899734 -1.33290842
 -1.15074233]

数组名称: test
形状: (2,)
数据类型: object

数据示例:
[array([-1.84482212, -1.71688634, -1.55992806, ...,  0.74114723,
        1.01362813,  0.99217488])
 array([-1.0576641 , -1.25509581, -0.98852189, ...,  1.21542715,
        1.33713149,  1.18483443])]

数组名称: train_m
形状: ()
数据类型: float64

数据示例:
87.9338669247619

数组名称: train_std
形状: ()
数据类型: float64

数据示例:
7.570672927879338

数组名称: t_train
形状: (10500,)
数据类型: int64

数据示例:
[ 5001  5002  5003 ... 15