In [5]:
import numpy as np

a=np.array([[1,2,3],[4,5,6,]])
print("a=",a)

b=np.expand_dims(a,-1) 
print("b=",b)

c=np.expand_dims(a,axis=0) 
print("c=",c)

a= [[1 2 3]
 [4 5 6]]
b= [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
c= [[[1 2 3]
  [4 5 6]]]
